/**
 * Seed content for the package silo (SOP §5 #2, #3). Used as fallback when the
 * CMS has no entry yet, so pages render on day one. Every price/timing is a
 * PLACEHOLDER (verify=false) and shows an "awaiting confirmation" stamp.
 */
export type SeedPackage = {
  slug: string;
  title: string;
  h1: string;
  facet: "duration" | "from-city" | "addon" | "traveller";
  duration: string;
  price_from: number;
  price_verified: boolean;
  answer_first: string;
  highlights: string[];
  itinerary: { day: number; title: string; description: string; stops?: string[] }[];
  inclusions: string[];
  exclusions: string[];
  faq: { question: string; answer: string }[];
};

const commonFaq = (name: string) => [
  {
    question: `What is the best time for the ${name}?`,
    answer:
      "October to March offers the most comfortable weather for temple darshan and coastal sightseeing across the Somnath–Dwarka circuit.",
  },
  {
    question: "Are temple darshan timings included in the plan?",
    answer:
      "Yes — the itinerary is sequenced around aarti and darshan windows. Exact timings are confirmed before travel as temple schedules can change on festival days.",
  },
  {
    question: "Is the price per person or per group?",
    answer:
      "Package prices shown are indicative starting points pending final confirmation. Your exact quote depends on group size, hotel tier and vehicle — share your dates for a firm price.",
  },
];

export const SEED_PACKAGES: SeedPackage[] = [
  {
    slug: "4-days-3-nights",
    title: "Somnath Dwarka Tour Package 4 Days 3 Nights — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package — 4 Days 3 Nights",
    facet: "duration",
    duration: "4 Days / 3 Nights",
    price_from: 13999,
    price_verified: false,
    answer_first:
      "The 4 days / 3 nights Somnath Dwarka tour package covers Dwarkadhish Temple, Nageshwar, Bet Dwarka, Somnath Temple and the light-and-sound show, with comfortable stays and private transport. It suits families and first-time pilgrims wanting the core circuit without rushing.",
    highlights: [
      "Dwarkadhish Temple darshan",
      "Nageshwar Jyotirlinga",
      "Bet Dwarka ferry",
      "Somnath Temple & aarti",
      "Somnath light & sound show",
    ],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, check in, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka", "Rukmini Temple"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive to Somnath via Porbandar; evening Somnath aarti & light-and-sound show.", stops: ["Porbandar", "Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure.", stops: ["Triveni Sangam"] },
    ],
    inclusions: ["3 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses", "Anything not listed in inclusions"],
    faq: commonFaq("4 days 3 nights Somnath Dwarka tour"),
  },
  {
    slug: "3-days-2-nights",
    title: "Somnath Dwarka Tour Package 3 Days 2 Nights — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package — 3 Days 2 Nights",
    facet: "duration",
    duration: "3 Days / 2 Nights",
    price_from: 10999,
    price_verified: false,
    answer_first:
      "The 3 days / 2 nights Somnath Dwarka package is a fast-paced pilgrimage covering Dwarkadhish, Nageshwar and Somnath temples with private transport. It works best for travellers short on time who still want darshan at both jyotirlinga-associated sites.",
    highlights: ["Dwarkadhish darshan", "Nageshwar Jyotirlinga", "Somnath Temple & aarti"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, Dwarkadhish darshan, Nageshwar.", stops: ["Dwarkadhish Temple", "Nageshwar"] },
      { day: 2, title: "Dwarka to Somnath", description: "Drive to Somnath, evening aarti & light-and-sound show.", stops: ["Somnath Temple"] },
      { day: 3, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["2 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("3 days 2 nights Somnath Dwarka tour"),
  },
  {
    slug: "5-days-4-nights",
    title: "Somnath Dwarka Tour Package 5 Days 4 Nights — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package — 5 Days 4 Nights",
    facet: "duration",
    duration: "5 Days / 4 Nights",
    price_from: 17999,
    price_verified: false,
    answer_first:
      "The 5 days / 4 nights Somnath Dwarka tour package covers the full circuit — Dwarkadhish, Nageshwar, Bet Dwarka, Porbandar and Somnath — at a relaxed pace with extra time for aarti, the light-and-sound show and coastal sightseeing. Ideal for families and senior travellers who prefer a comfortable, unhurried trip.",
    highlights: [
      "Dwarkadhish Temple darshan",
      "Nageshwar Jyotirlinga",
      "Bet Dwarka ferry",
      "Porbandar (Kirti Mandir)",
      "Somnath Temple, aarti & light show",
    ],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, check in, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka", "Rukmini Temple"] },
      { day: 3, title: "Dwarka to Porbandar to Somnath", description: "Drive via Porbandar; evening Somnath aarti & light-and-sound show.", stops: ["Porbandar", "Somnath Temple"] },
      { day: 4, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth, local sightseeing.", stops: ["Triveni Sangam", "Bhalka Tirth"] },
      { day: 5, title: "Somnath & departure", description: "Morning darshan and departure." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses", "Anything not listed in inclusions"],
    faq: commonFaq("5 days 4 nights Somnath Dwarka tour"),
  },
  {
    slug: "2-days-1-night",
    title: "Somnath Dwarka Tour Package 2 Days 1 Night — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package — 2 Days 1 Night",
    facet: "duration",
    duration: "2 Days / 1 Night",
    price_from: 8499,
    price_verified: false,
    answer_first:
      "The 2 days / 1 night Somnath Dwarka package is a quick darshan-focused trip covering Dwarkadhish and Somnath temples with private transport. It suits travellers on a tight schedule who want to complete both key darshans without an overnight-heavy itinerary.",
    highlights: ["Dwarkadhish darshan", "Somnath Temple & aarti", "Light & sound show"],
    itinerary: [
      { day: 1, title: "Dwarka darshan", description: "Arrive Dwarka, Dwarkadhish darshan, drive towards Somnath.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Somnath & departure", description: "Somnath darshan, aarti, Triveni Sangam, departure.", stops: ["Somnath Temple", "Triveni Sangam"] },
    ],
    inclusions: ["1 night hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("2 days 1 night Somnath Dwarka tour"),
  },
  {
    slug: "from-ahmedabad",
    title: "Somnath Dwarka Tour Package from Ahmedabad — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Ahmedabad",
    facet: "from-city",
    duration: "4–5 Days",
    price_from: 14999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Ahmedabad starts with pickup in Ahmedabad and covers Dwarka, Nageshwar, Bet Dwarka and Somnath by private road, returning to Ahmedabad. It is the most popular starting point given Ahmedabad's rail and air connectivity.",
    highlights: ["Ahmedabad pickup & drop", "Dwarka & Somnath temples", "Private road journey", "Flexible 4–5 day plan"],
    itinerary: [
      { day: 1, title: "Ahmedabad to Dwarka", description: "Depart Ahmedabad, drive to Dwarka, evening aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple." },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar; Somnath aarti & show." },
      { day: 4, title: "Somnath to Ahmedabad", description: "Morning darshan, return drive to Ahmedabad." },
    ],
    inclusions: ["Ahmedabad pickup & drop", "3–4 nights hotel", "Private AC vehicle", "Daily breakfast"],
    exclusions: ["Air/train fare to Ahmedabad", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Ahmedabad"),
  },
  {
    slug: "from-rajkot",
    title: "Somnath Dwarka Tour Package from Rajkot — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Rajkot",
    facet: "from-city",
    duration: "3–4 Days",
    price_from: 12999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Rajkot uses Rajkot as the base, cutting driving time to both temple towns. Expect pickup in Rajkot, darshan at Dwarka and Somnath, and a return to Rajkot over 3–4 days.",
    highlights: ["Rajkot pickup & drop", "Shorter drive times", "Dwarka & Somnath temples"],
    itinerary: [
      { day: 1, title: "Rajkot to Dwarka", description: "Depart Rajkot, drive to Dwarka, evening aarti." },
      { day: 2, title: "Dwarka to Somnath", description: "Nageshwar en route, Somnath aarti & show." },
      { day: 3, title: "Somnath to Rajkot", description: "Morning darshan, return to Rajkot." },
    ],
    inclusions: ["Rajkot pickup & drop", "2–3 nights hotel", "Private AC vehicle", "Daily breakfast"],
    exclusions: ["Fare to Rajkot", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Rajkot"),
  },
  {
    slug: "from-mumbai",
    title: "Somnath Dwarka Tour Package from Mumbai — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Mumbai",
    facet: "from-city",
    duration: "5–6 Days",
    price_from: 18999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Mumbai typically combines a flight or train to Gujarat with a private road circuit of Dwarka and Somnath. Plan 5–6 days to allow travel time plus unhurried darshan at both temples.",
    highlights: ["Flight/train guidance", "Full Dwarka–Somnath circuit", "5–6 day relaxed plan"],
    itinerary: [
      { day: 1, title: "Mumbai to Gujarat", description: "Travel to Ahmedabad/Rajkot by air or train; transfer." },
      { day: 2, title: "Dwarka", description: "Dwarkadhish darshan, Nageshwar, Bet Dwarka." },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar; Somnath aarti & show." },
      { day: 4, title: "Somnath", description: "Morning darshan, Triveni Sangam." },
      { day: 5, title: "Return to Mumbai", description: "Transfer to airport/station for return." },
    ],
    inclusions: ["Airport/station transfers in Gujarat", "4–5 nights hotel", "Private AC vehicle", "Daily breakfast"],
    exclusions: ["Mumbai–Gujarat air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Mumbai"),
  },
  {
    slug: "for-family",
    title: "Somnath Dwarka Family Tour Package — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package for Family",
    facet: "traveller",
    duration: "4–5 Days",
    price_from: 15999,
    price_verified: false,
    answer_first:
      "The family Somnath Dwarka tour package is paced for children and elders, with comfortable hotels, private transport, minimal walking between darshans and flexible meal stops. It covers the full Dwarka–Somnath circuit without long single-day drives.",
    highlights: ["Elder & child friendly", "Comfortable hotels", "Minimal walking", "Private transport"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Relaxed check-in, evening Dwarkadhish aarti." },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka at an easy pace." },
      { day: 3, title: "Dwarka to Somnath", description: "Comfortable drive, Somnath aarti & show." },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, departure." },
    ],
    inclusions: ["Family rooms", "Private AC vehicle", "Daily breakfast", "Assistance for elders"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("family Somnath Dwarka tour"),
  },
  {
    slug: "budget",
    title: "Budget Somnath Dwarka Tour Package — Itinerary & Price",
    h1: "Budget Somnath Dwarka Tour Package",
    facet: "traveller",
    duration: "3–4 Days",
    price_from: 8999,
    price_verified: false,
    answer_first:
      "The budget Somnath Dwarka tour package covers the essential darshans at Dwarka and Somnath using clean value hotels and shared or compact private transport. It keeps costs low while still sequencing the trip around aarti and darshan windows.",
    highlights: ["Value hotels", "Essential darshans", "Cost-efficient transport"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Check-in, Dwarkadhish darshan." },
      { day: 2, title: "Dwarka to Somnath", description: "Nageshwar en route, Somnath aarti." },
      { day: 3, title: "Somnath & departure", description: "Morning darshan, departure." },
    ],
    inclusions: ["Value hotel stays", "Transport", "Daily breakfast"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("budget Somnath Dwarka tour"),
  },

  // ---- Duration variants ----
  {
    slug: "1-day-somnath",
    title: "1 Day Somnath Tour Package — Itinerary & Price",
    h1: "1 Day Somnath Tour Package",
    facet: "duration",
    duration: "1 Day",
    price_from: 3499,
    price_verified: false,
    answer_first:
      "The 1 day Somnath tour package covers Somnath Temple darshan, the Triveni Sangam and Bhalka Tirth with private transport, ideal for travellers with a single day near Veraval. It is darshan-focused with no overnight stay.",
    highlights: ["Somnath Temple darshan", "Triveni Sangam", "Bhalka Tirth", "Evening aarti (time permitting)"],
    itinerary: [
      { day: 1, title: "Somnath in a day", description: "Somnath darshan, Triveni Sangam, Bhalka Tirth; evening aarti if time allows.", stops: ["Somnath Temple", "Triveni Sangam", "Bhalka Tirth"] },
    ],
    inclusions: ["Private AC vehicle for the day", "Driver allowance, toll, parking"],
    exclusions: ["Hotel stay", "Meals", "Air/train fare", "Personal expenses"],
    faq: commonFaq("1 day Somnath tour"),
  },
  {
    slug: "1-day-dwarka",
    title: "1 Day Dwarka Tour Package — Itinerary & Price",
    h1: "1 Day Dwarka Tour Package",
    facet: "duration",
    duration: "1 Day",
    price_from: 3499,
    price_verified: false,
    answer_first:
      "The 1 day Dwarka tour package covers Dwarkadhish Temple darshan, Nageshwar Jyotirlinga and Rukmini Temple with private transport, with an optional Bet Dwarka ferry if time allows. It suits travellers with a single day in Dwarka and no overnight stay.",
    highlights: ["Dwarkadhish darshan", "Nageshwar Jyotirlinga", "Rukmini Temple", "Bet Dwarka (optional)"],
    itinerary: [
      { day: 1, title: "Dwarka in a day", description: "Dwarkadhish darshan, Nageshwar, Rukmini Temple; Bet Dwarka ferry if time allows.", stops: ["Dwarkadhish Temple", "Nageshwar", "Rukmini Temple"] },
    ],
    inclusions: ["Private AC vehicle for the day", "Driver allowance, toll, parking"],
    exclusions: ["Hotel stay", "Meals", "Bet Dwarka ferry ticket", "Air/train fare"],
    faq: commonFaq("1 day Dwarka tour"),
  },
  {
    slug: "6-days-5-nights",
    title: "Somnath Dwarka Tour Package 6 Days 5 Nights — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package — 6 Days 5 Nights",
    facet: "duration",
    duration: "6 Days / 5 Nights",
    price_from: 21999,
    price_verified: false,
    answer_first:
      "The 6 days / 5 nights Somnath Dwarka tour package covers the full circuit at an unhurried pace — Dwarka, Nageshwar, Bet Dwarka, Porbandar and Somnath — with time for coastal sightseeing and a relaxed schedule. It suits families and senior travellers who prefer short driving legs.",
    highlights: ["Dwarkadhish & Bet Dwarka", "Nageshwar Jyotirlinga", "Porbandar", "Somnath aarti & light show", "Relaxed pace"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Porbandar", description: "Kirti Mandir and Sudama Temple; overnight en route.", stops: ["Porbandar"] },
      { day: 4, title: "Porbandar to Somnath", description: "Drive to Somnath; evening aarti & light-and-sound show.", stops: ["Somnath Temple"] },
      { day: 5, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth, local sightseeing.", stops: ["Triveni Sangam", "Bhalka Tirth"] },
      { day: 6, title: "Departure", description: "Morning darshan and departure." },
    ],
    inclusions: ["5 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses", "Anything not listed in inclusions"],
    faq: commonFaq("6 days 5 nights Somnath Dwarka tour"),
  },

  // ---- From-city variants ----
  {
    slug: "from-jamnagar",
    title: "Somnath Dwarka Tour Package from Jamnagar — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Jamnagar",
    facet: "from-city",
    duration: "3 Days / 2 Nights",
    price_from: 9999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Jamnagar starts at your doorstep and covers Dwarka, Nageshwar and Somnath with private transport. Jamnagar's proximity to Dwarka makes it one of the shortest and most economical starting points for the circuit.",
    highlights: ["Doorstep pickup in Jamnagar", "Dwarkadhish & Nageshwar", "Somnath aarti"],
    itinerary: [
      { day: 1, title: "Jamnagar to Dwarka", description: "Pickup, drive to Dwarka, Dwarkadhish darshan, Nageshwar.", stops: ["Dwarkadhish Temple", "Nageshwar"] },
      { day: 2, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Porbandar", "Somnath Temple"] },
      { day: 3, title: "Somnath & return", description: "Morning darshan, Triveni Sangam, return." },
    ],
    inclusions: ["2 nights hotel", "Private AC vehicle from Jamnagar", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Jamnagar"),
  },
  {
    slug: "from-vadodara",
    title: "Somnath Dwarka Tour Package from Vadodara — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Vadodara",
    facet: "from-city",
    duration: "4 Days / 3 Nights",
    price_from: 12999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Vadodara covers the full circuit — Dwarka, Nageshwar, Bet Dwarka and Somnath — with pickup in Vadodara and private transport. It suits travellers starting from central Gujarat who want a door-to-door plan.",
    highlights: ["Doorstep pickup in Vadodara", "Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti"],
    itinerary: [
      { day: 1, title: "Vadodara to Dwarka", description: "Drive to Dwarka (long leg), evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & return", description: "Morning darshan, Triveni Sangam, return to Vadodara." },
    ],
    inclusions: ["3 nights hotel", "Private AC vehicle from Vadodara", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Vadodara"),
  },
  {
    slug: "from-surat",
    title: "Somnath Dwarka Tour Package from Surat — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Surat",
    facet: "from-city",
    duration: "4 Days / 3 Nights",
    price_from: 13999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Surat covers Dwarka, Nageshwar, Bet Dwarka and Somnath with pickup in Surat and private transport. It is a comfortable door-to-door plan for travellers from south Gujarat.",
    highlights: ["Doorstep pickup in Surat", "Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti"],
    itinerary: [
      { day: 1, title: "Surat to Dwarka", description: "Drive to Dwarka (long leg), evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & return", description: "Morning darshan, Triveni Sangam, return to Surat." },
    ],
    inclusions: ["3 nights hotel", "Private AC vehicle from Surat", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Surat"),
  },
  {
    slug: "from-delhi",
    title: "Somnath Dwarka Tour Package from Delhi — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Delhi",
    facet: "from-city",
    duration: "5 Days / 4 Nights",
    price_from: 18999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Delhi combines a flight to Gujarat (typically Rajkot or Jamnagar) with a private-vehicle circuit of Dwarka, Nageshwar, Bet Dwarka and Somnath. Airfare is arranged separately or added on request.",
    highlights: ["Fly Delhi to Gujarat", "Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti & light show"],
    itinerary: [
      { day: 1, title: "Fly in & Dwarka", description: "Fly to Rajkot/Jamnagar, drive to Dwarka, evening aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth.", stops: ["Triveni Sangam"] },
      { day: 5, title: "Departure", description: "Morning darshan, transfer to airport." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle in Gujarat", "Airport transfers", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air fare (add on request)", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Delhi"),
  },
  {
    slug: "from-pune",
    title: "Somnath Dwarka Tour Package from Pune — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Pune",
    facet: "from-city",
    duration: "5 Days / 4 Nights",
    price_from: 17999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Pune combines a flight or train to Gujarat with a private-vehicle circuit of Dwarka, Nageshwar, Bet Dwarka and Somnath. Travel into Gujarat is arranged separately or added on request.",
    highlights: ["Fly/train Pune to Gujarat", "Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti & light show"],
    itinerary: [
      { day: 1, title: "Arrive & Dwarka", description: "Reach Gujarat, drive to Dwarka, evening aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth.", stops: ["Triveni Sangam"] },
      { day: 5, title: "Departure", description: "Morning darshan, transfer for return." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle in Gujarat", "Airport/station transfers", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare (add on request)", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Pune"),
  },
  {
    slug: "from-bangalore",
    title: "Somnath Dwarka Tour Package from Bangalore — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Bangalore",
    facet: "from-city",
    duration: "5 Days / 4 Nights",
    price_from: 18999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Bangalore combines a flight to Gujarat (typically Rajkot or Ahmedabad) with a private-vehicle circuit of Dwarka, Nageshwar, Bet Dwarka and Somnath. Airfare is arranged separately or added on request.",
    highlights: ["Fly Bangalore to Gujarat", "Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti & light show"],
    itinerary: [
      { day: 1, title: "Fly in & Dwarka", description: "Fly to Rajkot/Ahmedabad, drive to Dwarka, evening aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth.", stops: ["Triveni Sangam"] },
      { day: 5, title: "Departure", description: "Morning darshan, transfer to airport." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle in Gujarat", "Airport transfers", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air fare (add on request)", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Bangalore"),
  },
  {
    slug: "from-hyderabad",
    title: "Somnath Dwarka Tour Package from Hyderabad — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package from Hyderabad",
    facet: "from-city",
    duration: "5 Days / 4 Nights",
    price_from: 17999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package from Hyderabad combines a flight to Gujarat (typically Rajkot or Ahmedabad) with a private-vehicle circuit of Dwarka, Nageshwar, Bet Dwarka and Somnath. Airfare is arranged separately or added on request.",
    highlights: ["Fly Hyderabad to Gujarat", "Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti & light show"],
    itinerary: [
      { day: 1, title: "Fly in & Dwarka", description: "Fly to Rajkot/Ahmedabad, drive to Dwarka, evening aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth.", stops: ["Triveni Sangam"] },
      { day: 5, title: "Departure", description: "Morning darshan, transfer to airport." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle in Gujarat", "Airport transfers", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air fare (add on request)", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour from Hyderabad"),
  },

  // ---- Route / add-on variants ----
  {
    slug: "with-gir",
    title: "Somnath Dwarka Tour Package with Gir — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package with Gir",
    facet: "addon",
    duration: "5 Days / 4 Nights",
    price_from: 18999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package with Gir adds an Asiatic-lion safari at Sasan Gir to the temple circuit of Dwarka, Nageshwar and Somnath. It turns the pilgrimage into a temples-plus-wildlife trip; note that Gir closes for the monsoon.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti", "Gir lion safari"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath to Gir", description: "Morning darshan, drive to Sasan Gir, afternoon/next-morning safari.", stops: ["Sasan Gir"] },
      { day: 5, title: "Gir safari & departure", description: "Gir safari (subject to season/permits), departure.", stops: ["Gir National Park"] },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Gir safari permit & jeep (add on request)", "Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: [
      { question: "Is the Gir safari included in the price?", answer: "The safari permit and jeep are usually arranged separately as availability and rates vary; we add them to your quote on request. Gir also closes in the monsoon." },
      { question: "When is Gir open?", answer: "Gir National Park closes for the monsoon, roughly mid-June to mid-October. Confirm the current reopening date before planning the safari." },
    ],
  },
  {
    slug: "with-diu",
    title: "Somnath Dwarka Tour Package with Diu — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package with Diu",
    facet: "addon",
    duration: "5 Days / 4 Nights",
    price_from: 16999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package with Diu adds the beaches and Portuguese-era forts of Diu to the temple circuit of Dwarka, Nageshwar and Somnath. Diu sits close to Somnath, making it an easy relaxing extension after darshan.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti", "Diu beaches & fort"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath to Diu", description: "Morning darshan, drive to Diu, beaches and Diu Fort.", stops: ["Diu Fort", "Nagoa Beach"] },
      { day: 5, title: "Diu & departure", description: "Leisure morning, departure." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses", "Monument entry fees"],
    faq: commonFaq("Somnath Dwarka tour with Diu"),
  },
  {
    slug: "with-porbandar",
    title: "Somnath Dwarka Tour Package with Porbandar — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package with Porbandar",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 14999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package with Porbandar adds Gandhiji's birthplace — Kirti Mandir — and the Sudama Temple to the circuit of Dwarka, Nageshwar and Somnath. Porbandar sits on the road between the two temple towns, so it fits without extra driving.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Porbandar (Kirti Mandir, Sudama)", "Somnath aarti"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath via Porbandar", description: "Kirti Mandir and Sudama Temple en route; evening Somnath aarti.", stops: ["Porbandar", "Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour with Porbandar"),
  },
  {
    slug: "with-junagadh-girnar",
    title: "Somnath Dwarka Tour Package with Junagadh & Girnar — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package with Junagadh Girnar",
    facet: "addon",
    duration: "5 Days / 4 Nights",
    price_from: 17999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package with Junagadh & Girnar adds the Girnar hill temples and Junagadh's historic sites to the circuit of Dwarka, Nageshwar and Somnath. The Girnar climb is a significant trek, so allow a full day and reasonable fitness.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti", "Girnar temples & Junagadh"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath to Junagadh & Girnar", description: "Girnar hill temples (climb/ropeway) and Junagadh sights.", stops: ["Girnar", "Junagadh"] },
      { day: 5, title: "Junagadh & departure", description: "Uparkot Fort or local sights, departure." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Girnar ropeway ticket", "Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour with Junagadh Girnar"),
  },
  {
    slug: "with-statue-of-unity",
    title: "Somnath Dwarka Tour Package with Statue of Unity — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package with Statue of Unity",
    facet: "addon",
    duration: "6 Days / 5 Nights",
    price_from: 21999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package with the Statue of Unity combines the temple circuit of Dwarka, Nageshwar and Somnath with the world's tallest statue at Kevadia. Kevadia sits in eastern Gujarat, so this is a longer itinerary with a transfer day.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti", "Statue of Unity, Kevadia"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath to Kevadia", description: "Morning darshan, long drive towards Kevadia (Ekta Nagar).", stops: ["Kevadia"] },
      { day: 5, title: "Statue of Unity", description: "Statue of Unity, viewing gallery, gardens.", stops: ["Statue of Unity"] },
      { day: 6, title: "Departure", description: "Transfer to Vadodara/Ahmedabad for onward travel." },
    ],
    inclusions: ["5 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Statue of Unity tickets", "Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour with Statue of Unity"),
  },
  {
    slug: "with-ahmedabad",
    title: "Somnath Dwarka Tour Package with Ahmedabad — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package with Ahmedabad",
    facet: "addon",
    duration: "5 Days / 4 Nights",
    price_from: 15999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package with Ahmedabad adds a day in Gujarat's largest city — its UNESCO-listed old city, Sabarmati Ashram and Akshardham nearby — to the temple circuit of Dwarka, Nageshwar and Somnath. Ahmedabad is a convenient start or end point with the best flight connections.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti", "Ahmedabad old city & Sabarmati Ashram"],
    itinerary: [
      { day: 1, title: "Ahmedabad", description: "Sabarmati Ashram, old-city heritage walk, Akshardham (Gandhinagar).", stops: ["Sabarmati Ashram"] },
      { day: 2, title: "Ahmedabad to Dwarka", description: "Drive to Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 3, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 4, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 5, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses", "Monument entry fees"],
    faq: commonFaq("Somnath Dwarka tour with Ahmedabad"),
  },
  {
    slug: "with-dakor",
    title: "Somnath Dwarka Tour Package with Dakor — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package with Dakor",
    facet: "addon",
    duration: "5 Days / 4 Nights",
    price_from: 15999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package with Dakor adds the Ranchhodrai (Krishna) temple at Dakor in central Gujarat to the circuit of Dwarka, Nageshwar and Somnath. It suits Krishna devotees wanting to combine Dwarka with another important Krishna shrine.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti", "Dakor Ranchhodrai Temple"],
    itinerary: [
      { day: 1, title: "Dakor & onward", description: "Ranchhodrai darshan at Dakor, drive towards Saurashtra.", stops: ["Dakor Ranchhodrai Temple"] },
      { day: 2, title: "To Dwarka", description: "Reach Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 3, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 4, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 5, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["4 nights hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour with Dakor"),
  },

  // ---- Traveller & tier variants ----
  {
    slug: "for-couples-honeymoon",
    title: "Somnath Dwarka Tour Package for Couples & Honeymoon — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package for Couples & Honeymoon",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 15999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka couples and honeymoon package pairs darshan at Dwarka and Somnath with a relaxed pace, better hotels and coastal sunsets. It keeps driving legs comfortable and adds leisure time at Bet Dwarka and the Somnath seafront.",
    highlights: ["Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti & seafront", "Relaxed, couple-friendly pace"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple; leisure evening.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights hotel (upgraded)", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka couples tour"),
  },
  {
    slug: "for-senior-citizens",
    title: "Somnath Dwarka Tour Package for Senior Citizens — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package for Senior Citizens",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 14999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package for senior citizens covers both temples at a gentle pace with short driving legs, comfortable hotels close to the temples and assistance where possible. It prioritises easy darshan access and rest over packed sightseeing.",
    highlights: ["Comfortable, gentle pace", "Hotels near temples", "Dwarkadhish & Somnath darshan", "Assistance on request"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, rest, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar and Rukmini Temple; Bet Dwarka optional.", stops: ["Nageshwar"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar with breaks, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights hotel near temples", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Wheelchair/assistance charges", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka senior citizens tour"),
  },
  {
    slug: "group",
    title: "Somnath Dwarka Group Tour Package — Itinerary & Price",
    h1: "Somnath Dwarka Group Tour Package",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 11999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka group tour package is designed for families, friends and pilgrimage groups, with larger vehicles (tempo traveller or mini-bus), group-rate hotels and coordinated darshan. Per-person cost falls as group size grows.",
    highlights: ["Group vehicles (tempo/mini-bus)", "Group-rate hotels", "Coordinated darshan", "Lower per-person cost"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights group-rate hotels", "Tempo traveller / mini-bus", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka group tour"),
  },
  {
    slug: "for-nri-international",
    title: "Somnath Dwarka Tour Package for NRIs & International Travellers — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package for NRI & International Travellers",
    facet: "addon",
    duration: "6 Days / 5 Nights",
    price_from: 24999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka package for NRIs and international travellers offers an unhurried, fully-assisted circuit of Dwarka, Nageshwar, Bet Dwarka, Porbandar and Somnath, with airport pickups, English-speaking support and better hotels. It is built for visitors arriving from abroad who want everything handled.",
    highlights: ["Airport pickup & full assistance", "English-speaking support", "Dwarka, Bet Dwarka & Somnath", "Comfortable hotels, relaxed pace"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Airport pickup (Rajkot/Ahmedabad), transfer to Dwarka.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka darshan", description: "Dwarkadhish darshan, Nageshwar.", stops: ["Dwarkadhish Temple", "Nageshwar"] },
      { day: 3, title: "Bet Dwarka & Porbandar", description: "Bet Dwarka ferry, drive towards Porbandar.", stops: ["Bet Dwarka", "Porbandar"] },
      { day: 4, title: "Porbandar to Somnath", description: "Kirti Mandir, drive to Somnath, evening aarti.", stops: ["Somnath Temple"] },
      { day: 5, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth, rest.", stops: ["Triveni Sangam"] },
      { day: 6, title: "Departure", description: "Morning darshan, transfer to airport." },
    ],
    inclusions: ["5 nights hotel", "Private AC vehicle", "Airport transfers", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["International/domestic air fare", "Lunch & dinner", "Visa & travel insurance", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka NRI tour"),
  },
  {
    slug: "deluxe",
    title: "Deluxe Somnath Dwarka Tour Package — Itinerary & Price",
    h1: "Deluxe Somnath Dwarka Tour Package",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 17999,
    price_verified: false,
    answer_first:
      "The deluxe Somnath Dwarka tour package covers the core circuit of Dwarka, Nageshwar, Bet Dwarka and Somnath with upgraded 4-star-style hotels and a comfortable private vehicle. It is a step up from the standard plan without the premium of the luxury tier.",
    highlights: ["Upgraded hotels", "Dwarka & Bet Dwarka", "Nageshwar Jyotirlinga", "Somnath aarti & light show"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights deluxe hotel", "Private AC vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("deluxe Somnath Dwarka tour"),
  },
  {
    slug: "luxury",
    title: "Luxury Somnath Dwarka Tour Package — Itinerary & Price",
    h1: "Luxury Somnath Dwarka Tour Package",
    facet: "addon",
    duration: "5 Days / 4 Nights",
    price_from: 27999,
    price_verified: false,
    answer_first:
      "The luxury Somnath Dwarka tour package covers the full circuit with the best available hotels, a premium vehicle and priority-assisted darshan where possible. It suits travellers who want comfort and service to match the significance of the pilgrimage.",
    highlights: ["Best available hotels", "Premium vehicle", "Priority-assisted darshan (where possible)", "Full circuit at a relaxed pace"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti & light show.", stops: ["Porbandar", "Somnath Temple"] },
      { day: 4, title: "Somnath at leisure", description: "Triveni Sangam, Bhalka Tirth, coastal leisure.", stops: ["Triveni Sangam"] },
      { day: 5, title: "Departure", description: "Morning darshan and departure." },
    ],
    inclusions: ["4 nights luxury hotel", "Premium private vehicle", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("luxury Somnath Dwarka tour"),
  },

  // ---- Transport variants ----
  {
    slug: "by-car",
    title: "Somnath Dwarka Tour Package by Car — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package by Car",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 13999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package by car covers the full circuit in a private air-conditioned car with a driver, giving door-to-door flexibility around aarti and darshan timings. It is the most common way to do the roughly 233 km temple corridor.",
    highlights: ["Private AC car with driver", "Door-to-door flexibility", "Dwarka & Bet Dwarka", "Somnath aarti"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights hotel", "Private AC car", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour by car"),
  },
  {
    slug: "by-tempo-traveller",
    title: "Somnath Dwarka Tour Package by Tempo Traveller — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package by Tempo Traveller",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 12999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package by tempo traveller suits families and groups of roughly 8–17, covering the full circuit in a single spacious vehicle. It keeps everyone together and lowers the per-person cost versus multiple cars.",
    highlights: ["Spacious tempo traveller", "Best for groups of 8–17", "Everyone travels together", "Full Dwarka–Somnath circuit"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Arrive Dwarka, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Somnath", description: "Drive via Porbandar, evening Somnath aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights hotel", "AC tempo traveller", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour by tempo traveller"),
  },
  {
    slug: "by-bus",
    title: "Somnath Dwarka Tour Package by Bus — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package by Bus",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 7999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package by bus is a value option using coach transport on the temple corridor, best suited to larger pilgrimage groups. It trades some flexibility for a lower cost per person. Exact routing and coach type are confirmed on request.",
    highlights: ["Value coach travel", "Best for larger groups", "Dwarka & Somnath darshan", "Lower per-person cost"],
    itinerary: [
      { day: 1, title: "Arrival & Dwarka", description: "Reach Dwarka by coach, evening Dwarkadhish aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Rukmini Temple; Bet Dwarka optional.", stops: ["Nageshwar"] },
      { day: 3, title: "Dwarka to Somnath", description: "Coach to Somnath via Porbandar, evening aarti.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, departure." },
    ],
    inclusions: ["3 nights hotel", "Coach transport", "Daily breakfast"],
    exclusions: ["Air/train fare", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour by bus"),
  },
  {
    slug: "by-train",
    title: "Somnath Dwarka Tour Package by Train — Itinerary & Price",
    h1: "Somnath Dwarka Tour Package by Train",
    facet: "addon",
    duration: "4 Days / 3 Nights",
    price_from: 9999,
    price_verified: false,
    answer_first:
      "The Somnath Dwarka tour package by train uses rail to reach Gujarat (Dwarka and Veraval railheads) and a private vehicle for local sightseeing and the leg between the temple towns. Train tickets are arranged separately or added on request as availability varies.",
    highlights: ["Rail to Dwarka & Veraval", "Local sightseeing by private vehicle", "Dwarka & Somnath darshan", "Value option"],
    itinerary: [
      { day: 1, title: "Train to Dwarka", description: "Arrive Dwarka by train, Dwarkadhish darshan, evening aarti.", stops: ["Dwarkadhish Temple"] },
      { day: 2, title: "Dwarka sightseeing", description: "Nageshwar, Bet Dwarka, Rukmini Temple by local vehicle.", stops: ["Nageshwar", "Bet Dwarka"] },
      { day: 3, title: "Dwarka to Veraval/Somnath", description: "Travel to Somnath, evening aarti & light show.", stops: ["Somnath Temple"] },
      { day: 4, title: "Somnath & departure", description: "Morning darshan, Triveni Sangam, train departure from Veraval." },
    ],
    inclusions: ["3 nights hotel", "Local private vehicle for sightseeing", "Daily breakfast", "Toll, parking, driver allowance"],
    exclusions: ["Train fare (add on request)", "Lunch & dinner", "Personal expenses"],
    faq: commonFaq("Somnath Dwarka tour by train"),
  },
];

export const findSeedPackage = (slug: string) =>
  SEED_PACKAGES.find((p) => p.slug === slug) ?? null;
